version: 2
jobs:
   build:
     docker:
       - image: ubuntu:xenial
     working_directory: ~/
     steps:
       - checkout
       - run: pwd
       - run: ls
       - run: bash scripts/initialize_system.bash
