version: 2
jobs:
   build:
     docker:
       - image: iancolwell/xenial_user:latest
     steps:
       - checkout
       - run: pwd
       - run: ls
       - run: echo "$HOME"
       - run: bash scripts/initialize_system.bash
